# Generated by Django 4.2.16 on 2026-02-21 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('van', 'Van'), ('truck', 'Truck')], default='bike', max_length=10)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('aadhaar_photo', models.ImageField(blank=True, null=True, upload_to='driver_docs/aadhaar/')),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='driver_docs/license/')),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=30)),
                ('is_documents_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc', models.CharField(blank=True, max_length=15)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ocr_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('license', 'License')], max_length=10)),
                ('image', models.ImageField(upload_to='driver_docs/ocr/')),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_number', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_docs', to='driver.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_addresses', models.JSONField(blank=True, default=list)),
                ('preferred_payment', models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('cod', 'Cash on Delivery')], default='cod', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
