# Generated by Django 4.2.16 on 2026-02-21 04:54

import apps.bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=apps.bookings.models.generate_booking_id, max_length=20, unique=True)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('item_description', models.TextField(blank=True)),
                ('item_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('parcel', 'Parcel'), ('fragile', 'Fragile'), ('bulk', 'Bulk')], default='parcel', max_length=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('status_message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='bookings.booking')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DropLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('lat', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_locations', to='bookings.booking')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
