# Generated by Django 4.2.16 on 2026-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trackingupdate',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trackingupdate',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=12),
        ),
    ]
